"""Unit tests for the DocBook engine (planning.md Phase 5e).

Every fixture is a miniature version tree -- `html/` with a guide or two under it
-- because that is the unit the engine works in, and because most of
`architecture.md` §5.6's rules are only visible at that scale: whether a directory
is the root depends on where its stylesheet link lands, whether an anchor survives
depends on whether anything else points at it, and whether a page is navigable
depends on what its guide's book page links to.

The assertions are on the *corpus's* rules rather than on DocBook in general, and
the tests that look oddly specific are the ones where the tempting implementation
is wrong on real input:

- a duplicate directory is rejected on its stylesheet link, because it holds
  DocBook pages too and "holds a DocBook page" converts eight guides twice;
- `span.bold` is unwrapped before it is bolded, because 3,145 of them already
  contain a `strong` and `**` around `**` is `****`;
- the legal page comes from `div#footer`, because `is_legal_label` matches "third
  party" and `apiguide/thirdpartylibs.html` is a topic about packaging JARs;
- `a.ix` is dropped whole, because its `name` is prose with spaces and 0 of 3,347
  are ever referenced.
"""

from collections.abc import Mapping
from pathlib import Path

from docushift.engines.base import ConversionContext, Unit
from docushift.engines.docbook import CONTENT_ID, DocBookEngine
from docushift.engines.roots import find_output_roots
from docushift.models import SourceEngine
from docushift.reporting.findings import FindingsRun
from docushift.transforms.assets import AssetCopier

# -- fixtures in the small ------------------------------------------------------

MENU = (
    ("Welcome", "welcome/index.html"),
    ("Authoring", "authoring/index.html"),
)


def build(directory: Path, files: Mapping[str, str]) -> Path:
    for name, text in files.items():
        path = directory / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    return directory


def page(relative: str, title: str, body: str = "<p>Body.</p>", *,
         menu: tuple[tuple[str, str], ...] = MENU, footer: bool = True) -> str:
    """One page as DocBook XSL publishes it: generator comment, chrome, container.

    The chrome is real and it is all *outside* `div#mainContent`, which is the
    whole of §5.6.4: selecting the container is the chrome removal, so a test that
    left the chrome out would prove nothing.
    """
    up = "../" * (relative.count("/"))
    tabs = "".join(
        f'<span class="otherbook"><a href="{up}{href}">{label}</a></span>'
        for label, href in menu
    )
    footer_html = (
        '<div id="footer"><div id="user-footer"><ul>'
        f'<li id="legal-and-third-party-notices">'
        f'<a href="{up}welcome/legal-and-third-party-notices.html">Copyright</a> (c) 2026</li>'
        f'<li id="contact"><a href="{up}welcome/contact.html">Contact Us</a></li>'
        "</ul></div></div>"
    ) if footer else ""
    return (
        "<html><head>"
        "<!-- Generated by DocBook XSL Stylesheets V1.76.1 -->"
        '<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>'
        f"<title>{title}</title>"
        f'<link rel="stylesheet" href="{up}css/sbhelp.css" type="text/css"/>'
        "</head><body>"
        '<div id="header"><div id="banner">TIBCO StreamBase</div></div>'
        f'<p id="mainhelp-navmenu"><span class="currentbook">'
        f'<a href="{up}index.html">Home</a></span>{tabs}</p>'
        '<div id="breadcrumbs">You are here</div>'
        f'<div id="{CONTENT_ID}">{body}</div>'
        f"{footer_html}"
        "</body></html>"
    )


def titlepage(title: str) -> str:
    """The `div.titlepage` wrapper every generated page opens with."""
    return (
        '<div class="titlepage"><div><div>'
        f'<h1 class="title"><a name="{title.lower().replace(" ", "-")}"></a>{title}</h1>'
        "</div></div></div>"
    )


def toc(entries: str) -> str:
    return f'<div class="toc"><p><b>Contents</b></p><dl>{entries}</dl></div>'


def entry(href: str, label: str, children: str = "") -> str:
    nested = f'<dd><dl>{children}</dl></dd>' if children else ""
    return f'<dt><span class="article"><a href="{href}">{label}</a></span></dt>{nested}'


def javadoc(title: str) -> str:
    return (
        "<html><head><!-- Generated by javadoc (17) -->"
        f"<title>{title}</title></head><body><h1>{title}</h1></body></html>"
    )


# -- running one tree -----------------------------------------------------------


class Run:
    """One conversion of one extracted tree, with its units and its findings."""

    def __init__(self, units: list[Unit], findings: FindingsRun, tree: Path):
        self.units = units
        self.findings = findings
        self.tree = tree

    @property
    def unit(self) -> Unit:
        return self.units[0]

    def document(self, relative: str):
        for document in self.unit.documents:
            if str(document.relative) == relative:
                return document
        raise AssertionError(f"{relative} not among {self.names()}")

    def body(self, relative: str) -> str:
        return self.document(relative).body

    def names(self) -> list[str]:
        return sorted(str(d.relative) for d in self.unit.documents)

    def codes(self) -> dict[str, int]:
        tally: dict[str, int] = {}
        for finding in self.findings.all:
            tally[finding.code] = tally.get(finding.code, 0) + finding.count
        return tally

    def messages(self, code: str) -> list[str]:
        return [f.message for f in self.findings.all if f.code == code]

    def labels(self) -> list[str]:
        return [node.label for node in self.unit.nav]

    def under(self, label: str) -> list[str]:
        for node in self.unit.nav:
            if node.label == label:
                return [child.label for child in node.children]
        raise AssertionError(f"{label} not among {self.labels()}")


def run(tmp_path: Path, files: Mapping[str, str], api_roots: list[str] | None = None) -> Run:
    """Converts every unit in a tree, the way the driver does."""
    tree = build(tmp_path / "tree", files)
    output = tmp_path / "out"
    findings = FindingsRun("convert")
    context = ConversionContext(
        tree=tree,
        output=output,
        engine=SourceEngine.DOCBOOK,
        slug="str",
        version="11.2.1",
        product_name="TIBCO Streaming",
        api_roots=[tree / name for name in (api_roots or [])],
        output_roots=find_output_roots(tree, SourceEngine.DOCBOOK),
        findings=findings,
    )
    engine = DocBookEngine()
    units = []
    for root in engine.units(context):
        name = root.relative_to(tree).as_posix()
        context.assets = AssetCopier(root, SourceEngine.DOCBOOK, output / name if name else output)
        units.append(engine.convert_unit(context, root))
    return Run(units, findings, tree)


def one_page(tmp_path: Path, body: str, extra: Mapping[str, str] | None = None) -> Run:
    """A tree whose only guide holds one page. For the vocabulary tests."""
    return run(tmp_path, {
        "html/css/sbhelp.css": "body{}",
        "html/index.html": page("index.html", "StreamBase Documentation",
                                titlepage("StreamBase Documentation")),
        "html/authoring/index.html": page("authoring/index.html", "Authoring",
                                          titlepage("Authoring") + toc(entry("topic.html", "Topic"))),
        "html/authoring/topic.html": page("authoring/topic.html", "Topic",
                                          titlepage("Topic") + body),
        **(extra or {}),
    })


# -- the unit of work (§5.6.3) --------------------------------------------------


def test_the_unit_is_html_and_a_duplicate_directory_is_reported(tmp_path: Path) -> None:
    """A `str` version ships up to eight byte-identical duplicates of a guide.

    They hold DocBook pages, so a "holds a DocBook page" rule converts every
    duplicated guide twice. The stylesheet link is what separates them, and the
    rejection is reported rather than silent.
    """
    result = run(tmp_path, {
        "html/css/sbhelp.css": "body{}",
        "html/index.html": page("index.html", "Home", titlepage("Home")),
        "html/authoring/topic.html": page("authoring/topic.html", "Topic", titlepage("Topic")),
        # The duplicate: same bytes, one level up, linking a stylesheet that is
        # not under it.
        "authoring/topic.html": page("authoring/topic.html", "Topic", titlepage("Topic")),
    })

    assert [unit.name for unit in result.units] == ["html"]
    assert result.names() == ["authoring/topic.md", "index.md"]
    assert any("duplicate" in message for message in result.messages("DOCSET_SKIPPED"))


def test_output_mirrors_the_guide_directories(tmp_path: Path) -> None:
    """The guide directory is the only hierarchy this corpus has, so it is kept.

    Flat output would collide immediately: `index.html` alone is 24 pages in one
    version, one per guide.
    """
    result = run(tmp_path, {
        "html/css/sbhelp.css": "body{}",
        "html/index.html": page("index.html", "Home", titlepage("Home")),
        "html/welcome/index.html": page("welcome/index.html", "Welcome", titlepage("Welcome")),
        "html/authoring/index.html": page("authoring/index.html", "Authoring", titlepage("Authoring")),
    })

    assert result.names() == ["authoring/index.md", "index.md", "welcome/index.md"]


def test_the_landing_page_is_real_and_is_not_synthesized(tmp_path: Path) -> None:
    """`html/index.html` is a `div.book` with prose, not a frameset stub.

    The only engine of the four where `unit.landing` names a converted page rather
    than staying `None` for Phase 6 to fill.
    """
    result = one_page(tmp_path, "<p>Body.</p>")

    assert str(result.unit.landing) == "index.md"
    assert "index.md" in result.names()


# -- what is skipped, and why (§5.6.10) -----------------------------------------


def test_every_other_generator_in_the_package_is_skipped_by_name(tmp_path: Path) -> None:
    """Four generators ship in one package and the prose is a quarter of the files."""
    result = run(tmp_path, {
        "html/css/sbhelp.css": "body{}",
        "html/index.html": page("index.html", "Home", titlepage("Home")),
        "html/mms/index.html": "<html><head><!-- Doxia -->"
                               "<title>MMS</title></head><body>x</body></html>",
        "html/README.html": "<html><head><title>Read me</title></head><body>x</body></html>",
        "html/apidocs/index.html": javadoc("All Classes"),
        "html/apidocs/index-all.html": javadoc("Index"),
    }, api_roots=["html/apidocs"])

    assert result.names() == ["index.md"]
    assert result.unit.skipped == {
        "api-reference": 2, "foreign-generator": 1, "not-docbook": 1,
    }


def test_an_api_tree_with_no_recorded_root_is_still_not_converted(tmp_path: Path) -> None:
    """The generator marker catches it even where Stage 4 recorded no API root.

    `--input` runs have no `api_roots`, and a javadoc page converted as prose
    would be 2,400 pages of wrong output rather than a report line.
    """
    result = run(tmp_path, {
        "html/css/sbhelp.css": "body{}",
        "html/index.html": page("index.html", "Home", titlepage("Home")),
        "html/apidocs/index.html": javadoc("All Classes"),
    })

    assert result.names() == ["index.md"]
    assert result.unit.skipped == {"foreign-generator": 1}


# -- the container (§5.6.4) -----------------------------------------------------


def test_selecting_the_container_is_the_chrome_removal(tmp_path: Path) -> None:
    """Every header, menu, breadcrumb and footer is outside `div#mainContent`."""
    body = one_page(tmp_path, "<p>Real prose.</p>").body("authoring/topic.md")

    assert "Real prose." in body
    for chrome in ("TIBCO StreamBase", "You are here", "Contact Us", "Home"):
        assert chrome not in body


def test_a_page_with_no_container_is_reported_and_never_guessed(tmp_path: Path) -> None:
    """No `<body>` fallback: it would emit the header and breadcrumbs as prose."""
    result = run(tmp_path, {
        "html/css/sbhelp.css": "body{}",
        "html/index.html": page("index.html", "Home", titlepage("Home")),
        "html/authoring/broken.html":
            "<html><head><!-- Generated by DocBook XSL Stylesheets V1.76.1 -->"
            "<title>Broken</title></head><body><div id='header'>chrome</div>"
            "<p>Orphaned prose.</p></body></html>",
    })

    assert result.names() == ["index.md"]
    assert result.unit.skipped == {"no-content-container": 1}
    assert "CONTENT_MISSING" in result.codes()


def test_the_published_toc_is_not_emitted_into_the_prose(tmp_path: Path) -> None:
    """`toc.yml` reproduces it exactly; emitting it too puts a link list on top."""
    result = one_page(tmp_path, "<p>Body.</p>")

    assert "Contents" not in result.body("authoring/index.md")
    assert "[Topic]" not in result.body("authoring/index.md")


# -- titles (§5.6.6) ------------------------------------------------------------


def test_a_page_that_opens_at_h2_has_that_heading_promoted(tmp_path: Path) -> None:
    """921 pages open at `h2`: every `div.refentry` and every generated index.

    In 921 of 921 that heading's text is exactly `<title>`, so it is the page
    title rendered one level down -- and prepending a `#` above it would give the
    page two titles instead of one.
    """
    result = one_page(tmp_path, "", {
        "html/authoring/sbd.html": page(
            "authoring/sbd.html", "sbd",
            '<div class="refentry"><div class="refnamediv">'
            '<h2><span class="refentrytitle">sbd</span></h2>'
            "<p>Runs a StreamBase server.</p></div>"
            '<div class="refsynopsisdiv"><h2>SYNOPSIS</h2><p>sbd [options]</p></div></div>',
        ),
    })

    document = result.document("authoring/sbd.md")
    assert document.title == "sbd"
    assert document.body.startswith("# sbd\n")
    assert document.body.count("# sbd") == 1
    # Only the first heading moves: the sections below it stay below it.
    assert "## SYNOPSIS" in document.body


def test_a_page_with_no_heading_at_all_is_titled_from_the_title_tag(tmp_path: Path) -> None:
    """Unmeasured in this corpus, so the fallback is the conservative one."""
    result = one_page(tmp_path, "", {
        "html/authoring/bare.html": page("authoring/bare.html", "Bare", "<p>Prose only.</p>"),
    })

    assert result.body("authoring/bare.md") == "# Bare\n\nProse only."


def test_a_page_that_already_has_a_heading_gains_no_second_one(tmp_path: Path) -> None:
    body = one_page(tmp_path, "<p>Body.</p>").body("authoring/topic.md")

    assert body.startswith("# Topic\n")
    assert body.count("# Topic") == 1


# -- the class vocabulary (§5.6.7) ----------------------------------------------


def test_every_admonition_class_maps_and_the_printed_label_is_deleted(tmp_path: Path) -> None:
    """The class is the kind and the `h3.title` is the label GFM draws itself."""
    body = one_page(tmp_path, "".join(
        f'<div class="{kind}"><h3 class="title">{kind.title()}</h3>'
        f"<p>{kind} text.</p></div>"
        for kind in ("note", "tip", "important", "warning", "caution")
    )).body("authoring/topic.md")

    for kind in ("NOTE", "TIP", "IMPORTANT", "WARNING", "CAUTION"):
        assert f"> [!{kind}]" in body
    assert "### Note" not in body
    assert "ALERT_LABEL_UNMAPPED" not in body


def test_a_mapped_span_is_unwrapped_before_it_is_wrapped(tmp_path: Path) -> None:
    """3,145 `span.bold` contain a `strong`; `**` around `**` renders `****`."""
    body = one_page(tmp_path, (
        '<p><span class="bold"><strong>Save</strong></span> and '
        '<span class="command"><strong>sbd</strong></span> and '
        '<span class="emphasis"><em>maybe</em></span>.</p>'
    )).body("authoring/topic.md")

    assert "**Save**" in body and "****" not in body
    assert "`sbd`" in body
    # `span.emphasis` is never mapped: its `em` already says it.
    assert "*maybe*" in body and "**maybe**" not in body


def test_a_media_object_table_is_layout_and_is_unwrapped(tmp_path: Path) -> None:
    """1,126 single-cell tables wrapped around one image, purely for centring."""
    result = one_page(tmp_path, (
        '<div class="mediaobject"><table border="0" summary="manufactured viewport">'
        '<tr><td><img alt="Flow" src="../images/flow.png"/></td></tr></table></div>'
    ), {"html/images/flow.png": "PNG"})
    body = result.body("authoring/topic.md")

    assert "![Flow](" in body
    assert "|" not in body


def test_a_simplelist_table_becomes_a_list(tmp_path: Path) -> None:
    """192 of them: rows of one or two cells holding a link or a code span."""
    body = one_page(tmp_path, (
        '<table class="simplelist" border="0" summary="Simple list">'
        "<tr><td>alpha</td><td>beta</td></tr><tr><td>gamma</td><td></td></tr></table>"
    )).body("authoring/topic.md")

    assert "- alpha" in body and "- beta" in body and "- gamma" in body
    assert "|" not in body


def test_a_figure_caption_precedes_its_content_in_italic(tmp_path: Path) -> None:
    """`div.figure` is `a + p.title + div.figure-contents`, caption first."""
    result = one_page(tmp_path, (
        '<div class="figure"><a name="fig-flow"></a>'
        '<p class="title"><b>Figure 1. The flow</b></p>'
        '<div class="figure-contents"><p>Diagram.</p></div></div>'
    ))
    body = result.body("authoring/topic.md")

    assert body.index("*Figure 1. The flow*") < body.index("Diagram.")


def test_a_code_block_keeps_its_text_and_guesses_no_language(tmp_path: Path) -> None:
    """Nothing in the markup carries a language hint, so none is invented."""
    body = one_page(
        tmp_path, '<pre class="programlisting">sbd --help\nsbc dequeue</pre>'
    ).body("authoring/topic.md")

    assert "```\nsbd --help\nsbc dequeue\n```" in body


# -- anchors (§5.6.8) -----------------------------------------------------------


def test_only_referenced_anchors_survive_and_a_ix_never_does(tmp_path: Path) -> None:
    """10,753 `a[name]` are defined, 5,539 are ever named, and 0 `a.ix` are."""
    result = one_page(tmp_path, '<p>See <a class="link" href="other.html#kept">it</a>.</p>', {
        "html/authoring/other.html": page("authoring/other.html", "Other", (
            titlepage("Other")
            + '<p><a name="kept"></a>Kept.</p>'
            + '<p><a name="unused"></a>Unused.</p>'
            + '<p><a class="ix" name="streambase, running"></a>Indexed.</p>'
        )),
    })
    body = result.body("authoring/other.md")

    assert '<a id="kept"></a>' in body
    assert "unused" not in body
    assert "streambase, running" not in body
    assert result.document("authoring/other.md").anchors == {"kept"}


def test_a_bookmark_naming_no_anchor_loses_the_bookmark_and_keeps_the_link(
    tmp_path: Path,
) -> None:
    """9 of 5,548 fragments in the corpus resolve against nothing."""
    result = one_page(tmp_path, '<p><a class="link" href="other.html#gone">it</a></p>', {
        "html/authoring/other.html": page("authoring/other.html", "Other", titlepage("Other")),
    })

    assert "[it](other.md)" in result.body("authoring/topic.md")
    assert any("anchor absent" in m for m in result.messages("TOPIC_LINK_DANGLING"))


# -- links (§5.6.8) -------------------------------------------------------------


def test_an_intra_tree_link_is_rewritten_and_an_external_one_is_not(tmp_path: Path) -> None:
    result = one_page(tmp_path, (
        '<p><a class="olink" href="../welcome/index.html">Welcome</a> '
        '<a class="ulink" href="https://example.invalid/x">Away</a></p>'
    ), {"html/welcome/index.html": page("welcome/index.html", "Welcome", titlepage("Welcome"))})
    body = result.body("authoring/topic.md")

    assert "[Welcome](../welcome/index.md)" in body
    assert "[Away](https://example.invalid/x)" in body


def test_a_link_into_the_api_tree_is_reported_and_unlinked(tmp_path: Path) -> None:
    """The target exists on disk and has no converted counterpart, as in DITA."""
    result = one_page(
        tmp_path, '<p><a class="ulink" href="../apidocs/index.html">Javadoc</a></p>',
        {"html/apidocs/index.html": javadoc("All Classes")},
    )
    body = result.body("authoring/topic.md")

    assert "Javadoc" in body and "](" not in body
    assert any("apidocs" in m for m in result.messages("TOPIC_LINK_DANGLING"))


def test_a_cgi_olink_is_dropped_rather_than_emitted(tmp_path: Path) -> None:
    """`/cgi-bin/olink?sysid=…` is a cross-book link baked against a CGI script.

    There is no CGI in a static tree, so the text survives and the claim that it
    leads somewhere does not.
    """
    result = one_page(
        tmp_path, '<p><a class="olink" href="/cgi-bin/olink?sysid=str">Elsewhere</a></p>'
    )
    body = result.body("authoring/topic.md")

    assert "Elsewhere" in body and "cgi-bin" not in body
    assert any("cgi-bin" in m for m in result.messages("TOPIC_LINK_DANGLING"))


def test_an_image_is_resolved_and_copied_by_the_same_call(tmp_path: Path) -> None:
    """Invariant 13: the link and the copy come out of one resolution."""
    result = one_page(
        tmp_path, '<p><img alt="Flow" src="../images/flow.png"/></p>',
        {"html/images/flow.png": "PNG"},
    )

    assert "![Flow](../images/flow.png)" in result.body("authoring/topic.md")


# -- navigation (§5.6.5) --------------------------------------------------------


def test_the_menu_fixes_the_top_level_order_and_its_labels(tmp_path: Path) -> None:
    """It names 13 of 24 guides; the other 11 follow alphabetically by title."""
    result = run(tmp_path, {
        "html/css/sbhelp.css": "body{}",
        "html/index.html": page("index.html", "Home", titlepage("Home")),
        "html/welcome/index.html": page("welcome/index.html", "Welcome Guide", titlepage("Welcome")),
        "html/authoring/index.html": page("authoring/index.html", "Authoring Guide",
                                          titlepage("Authoring")),
        # Not in the menu, and alphabetically first -- it still comes last.
        "html/admin/index.html": page("admin/index.html", "Administration", titlepage("Admin")),
    })

    assert result.labels() == ["Welcome", "Authoring", "Administration"]


def test_the_book_toc_nests_and_a_part_page_does_not_duplicate_it(tmp_path: Path) -> None:
    """A book's TOC lists its parts; each part page carries a copy of its slice.

    The recursion is what reaches a section the book page never named; the filed
    guard is what stops the copy from placing everything twice.
    """
    result = run(tmp_path, {
        "html/css/sbhelp.css": "body{}",
        "html/index.html": page("index.html", "Home", titlepage("Home")),
        "html/authoring/index.html": page("authoring/index.html", "Authoring", (
            titlepage("Authoring")
            + toc(entry("part-one.html", "Part One", entry("alpha.html", "Alpha")))
        )),
        "html/authoring/part-one.html": page("authoring/part-one.html", "Part One", (
            titlepage("Part One")
            + toc(entry("alpha.html", "Alpha") + entry("beta.html", "Beta"))
        )),
        "html/authoring/alpha.html": page("authoring/alpha.html", "Alpha", titlepage("Alpha")),
        "html/authoring/beta.html": page("authoring/beta.html", "Beta", titlepage("Beta")),
    })

    assert result.under("Authoring") == ["Part One"]
    part = result.unit.nav[0].children[0]
    # Alpha comes from the book TOC's own nesting, Beta from the part page's --
    # and Alpha appears once, not once per TOC that names it.
    assert [child.label for child in part.children] == ["Alpha", "Beta"]
    assert "TOC_ORPHAN" not in result.codes()


def test_a_guide_with_no_toc_is_filed_by_its_link_graph(tmp_path: Path) -> None:
    """`adaptersguide`, `samplesinfo` and `lv-reference` ship no `div.toc` at all.

    Two hops from the book page take the corpus's unfiled count from ~430 to 42.
    """
    result = run(tmp_path, {
        "html/css/sbhelp.css": "body{}",
        "html/index.html": page("index.html", "Home", titlepage("Home")),
        "html/samplesinfo/index.html": page("samplesinfo/index.html", "Samples", (
            titlepage("Samples") + '<p><a href="embedded.html">Embedded</a></p>'
        )),
        "html/samplesinfo/embedded.html": page("samplesinfo/embedded.html", "Embedded", (
            titlepage("Embedded") + '<p><a href="ams.html">AMS</a></p>'
        )),
        "html/samplesinfo/ams.html": page("samplesinfo/ams.html", "AMS", titlepage("AMS")),
    })

    assert result.under("Samples") == ["Embedded", "AMS"]
    assert "TOC_ORPHAN" not in result.codes()


def test_a_page_nothing_reaches_is_filed_under_its_guide_and_counted(tmp_path: Path) -> None:
    """42 of 1,178 stay unfiled. That is normal here, and it is not a silence.

    Its guide is where it belongs, so it goes there rather than into an "Unfiled"
    bucket -- but the count is what says how well the three navigation sources
    did, so a run where it jumps is a run where a `div.toc` stopped parsing.
    """
    result = run(tmp_path, {
        "html/css/sbhelp.css": "body{}",
        "html/index.html": page("index.html", "Home", titlepage("Home")),
        "html/authoring/index.html": page("authoring/index.html", "Authoring",
                                          titlepage("Authoring")),
        "html/authoring/stray.html": page("authoring/stray.html", "Stray", titlepage("Stray")),
    })

    assert result.under("Authoring") == ["Stray"]
    assert result.codes()["TOC_ORPHAN"] == 1


# -- tail pages (§5.6.9) --------------------------------------------------------


def test_the_tail_pages_come_from_the_footer_and_not_from_the_title(
    tmp_path: Path,
) -> None:
    """`is_legal_label` matches "third party", so a title search picks the wrong page.

    `apiguide/thirdpartylibs.html` -- "Using Third-Party JARs and Native
    Libraries" -- is a technical topic about packaging, and it sorts first.
    """
    result = run(tmp_path, {
        "html/css/sbhelp.css": "body{}",
        "html/index.html": page("index.html", "Home", titlepage("Home")),
        "html/apiguide/thirdpartylibs.html": page(
            "apiguide/thirdpartylibs.html",
            "Using Third-Party JARs and Native Libraries",
            titlepage("Using Third-Party JARs and Native Libraries"),
        ),
        "html/welcome/legal-and-third-party-notices.html": page(
            "welcome/legal-and-third-party-notices.html", "Legal and Third Party Notices",
            titlepage("Legal and Third Party Notices"),
        ),
        "html/welcome/contact.html": page("welcome/contact.html", "Contact Us",
                                          titlepage("Contact Us")),
    })

    assert str(result.unit.legal) == "welcome/legal-and-third-party-notices.md"
    assert str(result.unit.support) == "welcome/contact.md"
    assert "TAIL_PAGE_MISSING" not in result.codes()


def test_an_absent_tail_page_is_reported_rather_than_invented(tmp_path: Path) -> None:
    """Invariant 10: the footer declares it, the file is gone, the report says so."""
    result = run(tmp_path, {
        "html/css/sbhelp.css": "body{}",
        "html/index.html": page("index.html", "Home", titlepage("Home")),
    })

    assert result.unit.legal is None and result.unit.support is None
    assert result.codes()["TAIL_PAGE_MISSING"] == 2
